## Supervised Learning

The model feeds on labelled data and makes prediction then or gives output. Supervised learning is used ton solve regression(finds continous value) or classification problem

# Regression

predicting stock prices, scores of student,aqi,house price prediction etc


# Classification
can be further split into multi class classification and binary class classification
spam detection,cat/dog detection,type of cancer etc

## Linear Regression

* when there are two variables basically
* one is dependent variable while the other one is independent variable
* we try to find a best fit line y=mx+c between the dependent variable and independent variable.
* We try to find the best fit line in such a way that it passes through all the predicted points.
* When to apply :  when we have continous data for ex we have study hours and score.
* error=actual-predicted
* we find best fit line by lowering the cost function(minimise the cost function)
* cost function measures how well the model's prediction matches the actual data.
* we try to achieve gradient descent using convergence algorithm i.e. we try to achieve global minima.
* we use this by controlling the learning rate, usually we take 0.01 if it's too small then convergence will happend slowly and if its high then it will converge randomly.
* generally in real life we have multiple input feature , so this algo is not much used.

In [2]:
import pandas as pd

In [3]:
insurance_data=pd.read_csv("insurance.csv")

In [4]:
insurance_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [5]:
import seaborn as sns

In [6]:
print(insurance_data["sex"].unique())
print(insurance_data["smoker"].unique())

<StringArray>
['female', 'male']
Length: 2, dtype: str
<StringArray>
['yes', 'no']
Length: 2, dtype: str

In [7]:
sexMap={
    "male":0,
    "female":1
}

smokerMap={
    "yes":1,
    "no":0
}

insurance_data["smoker"]=insurance_data["smoker"].map(smokerMap)
insurance_data["sex"]=insurance_data["sex"].map(sexMap)

X=insurance_data.drop(columns=["charges"])
y=insurance_data["charges"]

X=pd.get_dummies(X,columns=["region"],drop_first=True,dtype=int)

X["age_smoker"]=X["age"]*X["smoker"]
X["bmi_smoker"]=X["bmi"]*X["smoker"]

In [8]:
X.head()

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest,age_smoker,bmi_smoker
0,19,1,27.900,0,1,0,0,1,19,27.9
1,18,0,33.770,1,0,0,1,0,0,0.0
2,28,0,33.000,3,0,0,1,0,0,0.0
3,33,0,22.705,0,0,1,0,0,0,0.0
4,32,0,28.880,0,0,1,0,0,0,0.0

In [9]:
insurance_data

      age  sex     bmi  children  smoker     region      charges
0      19    1  27.900         0       1  southwest  16884.92400
1      18    0  33.770         1       0  southeast   1725.55230
2      28    0  33.000         3       0  southeast   4449.46200
3      33    0  22.705         0       0  northwest  21984.47061
4      32    0  28.880         0       0  northwest   3866.85520
...   ...  ...     ...       ...     ...        ...          ...
1333   50    0  30.970         3       0  northwest  10600.54830
1334   18    1  31.920         0       0  northeast   2205.98080
1335   18    1  36.850         0       0  southeast   1629.83350
1336   21    1  25.800         0       0  southwest   2007.94500
1337   61    1  29.070         0       1  northwest  29141.36030

[1338 rows x 7 columns]

In [10]:
X

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest,age_smoker,bmi_smoker
0,19,1,27.900,0,1,0,0,1,19,27.90
1,18,0,33.770,1,0,0,1,0,0,0.00
2,28,0,33.000,3,0,0,1,0,0,0.00
3,33,0,22.705,0,0,1,0,0,0,0.00
4,32,0,28.880,0,0,1,0,0,0,0.00
...,...,...,...,...,...,...,...,...,...,...
1333,50,0,30.970,3,0,1,0,0,0,0.00
1334,18,1,31.920,0,0,0,0,0,0,0.00
1335,18,1,36.850,0,0,0,1,0,0,0.00
1336,21,1,25.800,0,0,0,0,1,0,0.00
1337,61,1,29.070,0,1,1,0,0,61,29.07

In [11]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [12]:
from sklearn.linear_model import LinearRegression

model=LinearRegression()

model.fit(X_train,y_train)

LinearRegression()

In [13]:
y_pred=model.predict(X_test)

In [14]:
from sklearn.metrics import r2_score

r2=r2_score(y_test,y_pred)
print("r-squared : ",r2)

# This values lies between 0 & 1
# closer to 0 means model is unable to explain 
# 1- means perfect 
# normal range 0.7-0.85

# we use adjusted R squared error to measure well because sometimes on addition of some
# random feature also affects R2 value but which is not true actually 
# This is the problem which is solved by adjsuted R squared

r-squared :  0.865231697953168

In [15]:
X_test

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest,age_smoker,bmi_smoker
764,45,1,25.175,2,0,0,0,0,0,0.000
887,36,1,30.020,0,0,1,0,0,0,0.000
890,64,1,26.885,0,1,1,0,0,64,26.885
1293,46,0,25.745,3,0,1,0,0,0,0.000
259,19,0,31.920,0,1,1,0,0,19,31.920
...,...,...,...,...,...,...,...,...,...,...
109,63,0,35.090,0,1,0,1,0,63,35.090
575,58,1,27.170,0,0,1,0,0,0,0.000
535,38,0,28.025,1,0,0,0,0,0,0.000
543,54,1,47.410,0,1,0,1,0,54,47.410
846,51,1,34.200,1,0,0,0,1,0,0.000

In [16]:
n=X_test.shape[0]
p=X_test.shape[1]

adjusted_r2=1-((1-r2)*(n-1)/(n-p-1))
print("adjusted r2 :",adjusted_r2)

adjusted r2 : 0.8599877951497893

## Feature Engineering

In order to get better model performance we do feature engineering i.e. either we add new features or remove existing features.
There are differnet techniques

1. One-Hot Encoding - performed  and model score imporved from 78.11 to 78.35 

2. Creating useful derived features- BMI<18 ->underweight
                                     BMI>25 ->overweight
                                     BMI(18-25)->normal

3. Merge Two or more features to get better insights- for ex a person who is a smoker and high BMI has to pay more Insurance. (performed above and model accuracy - 78 --->> 86)

4. Scaling Numeric Features - for ex if data has salary which is in lacs so model get influenced by this large value. So we have to control this i.e. all features must have equal impact. So this can be done using standardisation and normalisation

5. Feature Selection - Remove the unwanted data

## Overfitting and underfitting

# overfitting

 When model becomes complex. Instead of identifying patterns model try to remember the data. 
 It performs very well on training data but performs poor on testing data. It tries to pass through all the points i.e. even try to pass through outliers but it will give poor performance on testing data. It is a condition of Low bias and high Variance.

 # Underfitting

 When model becomes too simple. It is not be able to understand even the simple data. The training accuracy is low i.e. performs poorly om testing data and training data.It is a condition of high Bias and low variance.For ex if data is following a quadratic graph and we try to implement linear regression to it then model becomes too much simple and gives poor output.

 We aim to create a generalised model i.e. a condition of low bias and low variance.

In [19]:
## how to check whether our model is underfit or overfit

# we use r2 score for this (for training and testing)

y_train_pred=model.predict(X_train)
r2_train=r2_score(y_train,y_train_pred)

print("training data r2  : ",r2_train)
print("test data r2 : ",r2)

training data r2  :  0.8340713711218875
test data r2 :  0.865231697953168

## Overcoming Problems (overfitting and underfitting)

1. regularisation :  It helps in generalisation thereby preventing overfitting.So in this case since there is low bias so cost function becomes zero. So we ourself add some penalty so that cost function never becomes zero

* Lasso Regression :  Also known as L1 Regularisation. here we modify the cost function a little bit . So we add lambda*(parameters)
* Ridge Regression: Also known as L2 Regularisation.
* Elastic Net : It is a combination of lasso regression and ridge regression.